services:
  user.repository:
    class: "users/user.memory.repository"
    arguments: ["@user.data-mapper"]
  user.service:
    class: "users/user.service"
    arguments: ["@user.repository", "@task.repository"]
  user.data-mapper:
    class: "users/user.data-mapper"

  board.repository:
    class: "boards/board.memory.repository"
    arguments: ["@board.data-mapper"]
  board.service:
    class: "boards/board.service"
    arguments: ["@board.repository", "@task.repository"]
  board.data-mapper:
    class: "boards/board.data-mapper"

  task.repository:
    class: "tasks/task.memory.repository"
    arguments: ["@task.data-mapper"]
  task.service:
    class: "tasks/task.service"
    arguments: ["@task.repository", "@board.repository"]
  task.data-mapper:
    class: "tasks/task.data-mapper"
